package com.base

import io.reactivex.annotations.Experimental

interface Remote {
    /**
     * The Generic Api Provider Which can be Accessed from Any Consumer Module and Provides the Api Interface object Reference Generated by RetroFit.
     *
     * @param T the Type of Api Interface
     * @param baseUrl Your Base URL
     * @param apiClass Class Of Type of your Api Interface
     * @return the Api Interface object
     */
    fun <T> getApi(baseUrl: String, apiClass: Class<T>): T?

    /**
     * The Generic Self Signed Api Provider Which can be Accessed from Any Consumer Module and Provides the Api Interface object Reference Generated by RetroFit.
     *
     * Place all of your custom certificates in assets/cert/<here>
     *
     * @param T the Type of Api Interface
     * @param baseUrl Your Base URL
     * @param apiClass Class Of Type of your Api Interface
     * @return the Api Interface object
     */
    fun <T> getSelfSignedApi(baseUrl: String, apiClass: Class<T>): T?

    /**
     * The Generic Unsafe Api Provider Which can be Accessed from Any Consumer Module and Provides the Api Interface object Reference Generated by RetroFit.
     *
     * Unsafe  = This Will ignore SSL Certification Validity and Allow All from TrustManager
     *
     * @param T the Type of Api Interface
     * @param baseUrl Your Base URL
     * @param apiClass Class Of Type of your Api Interface
     * @return the Api Interface object
     */
    @Deprecated("Don't use this Method on production Build. Its Suggested not to use Unsafe Version of Retrofit on Production Builds.")
    @Experimental
    fun <T> getUnsafeApi(baseUrl: String, apiClass: Class<T>): T?

}